package:
  name: "minicontourfinder"
  version: "1.0.7"

source:
  git_url: https://github.com/isgilman/MiniContourFinder

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - pillow
    - py-opencv
    - pyperclip
    - pyqt5-sip
    - pytesseract
    - python
    - pandas
    - jupyter
    - tqdm

about:
  home: https://github.com/isgilman/MiniContourFinder
  license: GNU General Public License v3 (GPLv3)
  license_familY: GNU
  license_file: LICENSE
  summary: "Lightweight image segmentation software for biological images"

extra:
  recipe-maintainers:
    - Ian S. Gilman